### ISSUE TITLE
Improve Burst-Traffic Resilience

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#148]
Basically a catch-all issue for methods in which to improve the site's resilience against large traffic spikes. I've forgotten (sorry @czlee) if it was primarily the volume of inbound traffic that was behind the Dunedin tab results crash; but performance was certainly slow regardless of the crash. Some ideas for improvement:

- [ ] Implement a cache status and configuration page; [like so](http://effbot.org/zone/django-memcached-view.htm) so we can have at least some idea of how big our memcache server would need to be
    - [x] Possibly follow that up or supplant that with [New Relic](http://newrelic.com) for more precise monitoring
- [ ] Do some basic testing/validation (if just turning caching it off and on again with benchmarks) to ensure Django's caching and memcache is working and configured optimally. For example, I think memcache mostly works by keeping commonly-accessed database records in memory. However, when a tab is released, nearly all our data is being frequently accessed so its efficacy may be limited.
- [ ] If that is the case we should look at [caching views](https://docs.djangoproject.com/en/dev/topics/cache/#the-per-view-cache) or [caching HTTP responses](https://blog.disqus.com/post/62187806135/scaling-django-to-8-billion-page-views). We have relatively few pages, and the tab-release pages don't really need to have their cache invalidated often, so this is probably our best solution for improving resilience.  
- [x] Current emoji support generates enormous numbers of HTTP requests for individual images. Which is stupid. Now that native (ie non-image based) support for Emoji is [relatively widespread](http://blog.getemoji.com/post/73341182572/its-2014-why-doesnt-chrome-support-emoji) we should switch.

**Comment by czlee** [comment]
See #130.

The speaker and team tab pages take way too many database hits to generate, so they can take a good number of seconds on request. It's this combined with volume that crashed the server. Specifically, it caused H12 errors. See #130.

**Comment by philipbelesky** [comment]
Hmm, in theory caching the HTTP response for the speaker and team tab pages should alleviate most of the need for an async process? If only the first hit generates a 1-2 second long process and all others serve straight from caches, that might be enough for things to hold up.

**Comment by czlee** [comment]
On the night we were talking about 20 to 30 seconds. So you're right—once the response is cached, we're fine again. The problem is that it's really hard to get that first cached version in, because about a dozen people will be trying to look at it before the first cache, and all of those requests will spawn a process to generate the entire page. So we have the problem before we have a cached version, and that prevents us from ever getting a cached version.

It takes a lot less time now, presumably because there aren't multiple users competing for processor time. A lot of this is speculation though—I don't have any numbers to back up my theory.

More generally, though, if we want things to robust we should probably make it async—it seems dodgy to me to have a website that breaks, as opposed to merely degrades in performance, when the cache becomes slow. Or rewrite the view logic so that the number of database hits is O(1), rather than O(n) in the number of debates.

**Comment by philipbelesky** [comment]
Switching the server could also be a good idea: http://blog.etianen.com/blog/2014/01/19/gunicorn-heroku-django/

**Comment by philipbelesky** [comment]
And on database hit reductions: https://docs.djangoproject.com/en/1.7/topics/db/optimization/

**Comment by philipbelesky** [comment]
Closing this in favour of future issues that are more focused on particular performance optimisations.
