### ISSUE TITLE
Data entry GUIs

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#220]
This is a feature I've started on ```importer-gui```. Essentially it acts as a way of doing data entry for users that are not comfortable with the command line and/or as a way of easily setting up tournaments that have 'simple' data sets: either tournaments that have few teams/people, or for high school debating leagues that do not need high levels of fidelity (ie the speakers don't need real names). 

A major benefit of this section would be that existing installations could be reused more easy, and that creating a new instance would only require someone with command line knowledge for the initial setup, at which point it could be handed over to the organisers to finish the setup using this GUI. 

Three main functions come to mind:

1. For institutions: a ```textarea``` that takes a simple textual list of institutions (see the instructions in```templates/data/add_institutions```)
2. For teams: a form with a list of institutions, and a numeric input for the number of new teams to add for each institution. Once submitted these teams are then created with anonymous speakers and generic team names (1,2,3), but are then passed to a second page where the speaker/team names are presented for editing. At worst these would just be textual input fields, but maybe there's a better UI for that?
3. For adjudicators: a process that largely mirrors the process as for teams.
4. Other sections/functions may be added as needed to fit the WADL spec

**Comment by czlee** [comment]
Sounds good. Questions:

(1) The `importer` module basically expects to be given a CSV file. Would it seem sensible to you for the GUI basically to convert whatever input it receives, into a CSV file?

I think in Python there are ways to make something appear like a file without actually writing a file. Like you can open some sort of stream directly to the module or something, the point is the interface has to "look like" a CSV file.

(2) Do you want to add a CSV file uploader to the GUI first? As in, the user selects a file to upload in the GUI, then it runs it through the same importer as the tournament management command currently does.

On another note: It seems like an open question to me how to make the interface both easy to use and efficient (or if there's a trade-off between them!), so long as it's not loaded with dropboxes I guess it'll be fine. Like maybe it'd be easier for a user, when inputting teams, to select an institution on each row by typing the first few characters of the institution's name, rather than getting all those numbers right (what if they make a mistake?), but I'm not sure.

**Comment by philipbelesky** [comment]
1. I am unclear whether it should interface with the ```importer``` as its importing a very simple data set which could be handled simply within the form processing. My mind might change on this as it is implemented though, so I'm not really sure.
2. I think uploading a CSV might fall slightly too far to the towards the difficult end of the spectrum. Ideally it should be as simple as possible to copy/paste values from a google spreadsheet, which seems to be the normal workflow. Even for things like speaker names, it might be easier to just put a comma-seperated list of names in an ```input``` for each team. It would require individual copy+pastes from the teams list to enter, but at a small tournament thats still only takes a few minutes.

**Comment by czlee** [comment]
1. Fair.

2. Possibly. Importing strikes me as the kind of thing where what is easiest/fastest is heavily context-dependent---for example, on what the original format of the registration data is (which, in turn, depends on how pedantic the registration officer is), as well as the size of the tournament, and how much tournaments care about particular things. So in general terms I'm not really opposed to having various interfaces added over time. I know it makes it more complex because then tab directors have to figure out which one they want to use, but that's a hit I'm willing to take.

    Random thought, I wonder if we could add something that could import directly from Google Sheets, like using a Google Sheets API or something [(like this?)](https://developers.google.com/apps-script/guides/sheets)
