### ISSUE TITLE
Provide a GUI for regenerating a round

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#231]
Just because this just came up at Joynt, and has done so previously: it would be good to have a button on the draw page that resets the round to a ```None``` state (and properly deletes redundant `Debate` objects etc). It seems to come up relatively commonly, and seems like a better idea than relying on undocumented (I think) changes to on the Django backend.

**Comment by czlee** [comment]
As a note, on the develop branch, the management command
```
$ python manage.py deletedraw <round_seq>
```
does exactly this. On the master branch, until the 0.8 release, it's
```
$ python data/utils/delete_draw.py <round_seq>
```

We could provide a front-end for this (with appropriate "are you sure? are you really, really sure? this can't be undone!" messages), and if this is done, the relevant code from `draw/management/commands/deletedraw.py` should be abstracted into a `draw/dbutils.py` file, similarly to `results/dbutils.py`, so that both the front-end and management commands are just a wrapper.
