### ISSUE TITLE
Do not let users generate a draw without previous results having been entered

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#255]
I haven't completely replicated what happened with nujpds, but it seemed like the root issue was that the draw was failing because in the previous rounds not all results had been entered. 

So it seems like we should prevent this behaviour from occurring. I would think it is better to stop it at the point of draw generation rather than round advancement, but that's just me. Thoughts?

Any warning (or blocking of an action) would also need to ensure the draw rules aren't something like round-robin where previous results are not needed.

**Comment by czlee** [comment]
I think a warning will do, I tend to think that if tab directors want to take risks it's up to them. Also, I'm happy to consider whether the draw can still be done (technically, if inaccurately) without a complete results. It's meant to run on standings, not results, and standings should always be fully defined, so I'm still intrigued as to why it failed.

As for when, I don't really have a strong inclination, but if I were to pick one I guess I'd say draw generation, since that's when the error actually happens. That said, don't we already have a warning before round advancement of ballots aren't all in?

**Comment by philipbelesky** [comment]
Agree that a warning should be sufficient. Will check if there is a warning before round advancement. Is it worth creating a new issue focusing on why the standings were not fully defined?

**Comment by czlee** [comment]
Yeah, probably, I should probably have a look. It might be that there's nothing wrong, but it might not be.

**Comment by philipbelesky** [comment]
Have added a second warning just before the draw generation stage. Closing this issue —  if we want to either do a more thorough investigation of nujpds or allow draw generation without full results that should probably be a second issue.
