### ISSUE TITLE
Deploy to heroku error

### ISSUE THREAD

**Issue by wytanj** [czlee/tabbycat#301]
[Log.txt](https://github.com/czlee/tabbycat/files/173825/Log.txt)

Issue was encountered. It seems:

django.db.utils.ProgrammingError: relation "dynamic_preferences_globalpreferencemodel" does not exist

is causing the issue. Is heroku deploying from the development branch or master? Just checking. Could it be a table missing?

Thanks.

Encountered with two separate heroku accounts.

**Comment by philipbelesky** [comment]
Hey, thanks for reporting this. Turns out I broke this in 94661ac1a53917cf1c3136c107d3ab3435b91c85 as it runs a command that doesn't work until the initial migrations are made, thus breaking heroku deploys. I've just removed it, checked that it works, and updated the release. Should be all good now!
