### ISSUE TITLE
BallotSubmissions not creating SpeakerScoreByAdj in some circumstances

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#304]
Just came up with WADL, iirc this also came up with them last year and possibly in other circumstances. Symptom is that SpeakerScores get created as normal, but not SpeakerScoreByAdj so when going to confirm the ballot the scores are blank.

**Comment by philipbelesky** [comment]
Think I've found the problem: a adj's SpeakerScoreByAdj are deleted when the draw is updated (because adjs can adj multiple debates in a round, and allocations are not done until the debates take place, this can happen often).

**Comment by czlee** [comment]
Wait, so that would mean it only happens if you edit the draw after the first result is entered? Or does it delete _all_ of an adj's speaker-score-by-adjs whenever you save it?

**Comment by czlee** [comment]
Also—relates to #166, though only indirectly.

**Comment by philipbelesky** [comment]
Testing that atm. It seems that just saving a draw (without making any edits) is enough to wipe at least some (possibly all) of the Speaker Scores for that round.

**Comment by philipbelesky** [comment]
Sorry earlier when I said draw I really meant the adjudicator allocation. IE by going to Edit Adjs then saving the page (without changing the allocation) removed the SpeakerScoreByAdj objects.

**Comment by czlee** [comment]
Sorry, I meant that too. I guess we've assumed in the past that adjs should be locked down before you start entering results, but that's not always the case?

#166 is probably directly relevant actually. iirc we delete and recreate all DebateAdjudicator objects when saving an allocation. Since a SpeakerScoreByAdj is tied to a DebateAdjudicator, it follows that all associated SpeakerScoreByAdj objects would be deleted.

So then #166 is probably the proper fix. I mean, there's also a whole design question about what we _should_ do with the results of a debate whose adjudicators change.

**Comment by czlee** [comment]
Oh, #166 isn't actually the same thing, just similar. That one relates to the score objects themselves; this one's the DebateAdjudicators. I'll deal with both.
