### ISSUE TITLE
Remove redirect (possibly just for admins)

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#314]
Given we are now pointing people towards using the 'create a tournament' wizard, and this is located on the root page, people can't access that root page when there is only one tournament because they get redirected. At least for admin users the redirect should not work this way.

**Comment by czlee** [comment]
I agree with this, but for sites with only one tournament, it's still useful to have the redirect since there are a lot of sites where going through that extra page is just a pain.

How about: Add a "New Tournament" item to tournaments spinner (the one in the top left of every admin page), that is always there?

On this note, we should probably also have a link to the public site from the admin page, just for convenience, just like in the left-hand bar somewhere.

**Comment by philipbelesky** [comment]
1. I'm not sure it's that much of a pain for admins — its one click that doesnt happen often and it presents you with a choice (admin or public) that may be useful (whereas for the public there is no choice)

2. What do you mean by spinner? The dropdown menu? If so, yes.

3. If the homepage no longer redirects we could just add a link to the homepage in the dropdown menu (there's one in the footer also atm)

**Comment by czlee** [comment]
To be honest, I like to be able to type in just the root URL and have it go to the admin overview page. That feels like the most natural home to me for a site with one tournament. (In other words, as an admin, I find it a pain to click through the root page when I'm always going to the same place.)

Thinking about it more, I don't really find the root page the best place to choose between the admin and public sites. If I'm an admin, most of the time I am interacting with the admin site, and if I want to see the public site, it's only to check that it's doing what I want. So I'd suggest putting a link to the public site in the left-hand bar instead, either at the top or the bottom, and I think that should open the public site in a new tab.

Another option, not mutually exclusive: Put what is currently the root page at some other URL, and have root redirect there, so that root always redirects somewhere. Then also provide a link to this page in the dropdown. (Though it's not clear how useful this would be right now, since the only additional link there is the "create new tournament" link, so I probably wouldn't do this.)

By "spinner" I meant dropdown, sorry, got terms mixed up, though I think I got it from Android, which calls that thing a spinner for some reason.

**Comment by philipbelesky** [comment]
Hmm, my preference is to keep the navigation model as close to the conceptual model as possible. In my mind, the latter is:

- Tier 0: Root page (all users)
- Tier 1: Tournament Overview (public) OR Tournament Overview (admin)
- Tier 2: Top level sections for admin/public pages
- Tier 3: Sub pages for top level sections

Currently the dropdown in the top left lets admin and public users switch to the tournament overview of any other tournament. For public it also has a root page link; for admins it should have the same. 

If we want to add a shortcut for admins to jump to the public versions of a tournament maybe the public sites should be listed in that dropdown as well. That would keep that dropdown as a method for accessing all Tier0/1 pages while the rest of the menu works for Tier 2
s.

**Comment by philipbelesky** [comment]
Also this perhaps confuses the conceptual somewhat, but "New Tournament" could be a link under "Edit Data". However because admin users first encounter "New Tournament" at the root level page my preference is for leaving it there. Not having a redirect is a mild inconvenience for experienced admins but I don't know if its inconvenient enough to compromise the clarity/consistency of the navigation for less experienced admins.

**Comment by czlee** [comment]
Okay, I guess my preference is for the navigation model to follow user habits (or what I perceive to be user habits), in the same way that Facebook doesn't make you click through a root page for you to get to your News Feed.

A few claims:
1. An admin who visits a Tabbycat site almost always wants to go to the admin site for the tournament they are interested in. Where they want to go to the public site, it's normally only to check that it's doing what they expect (because if they wanted information, they'd just check the relevant admin page), so they are normally opening it from the admin site.
2. A user who is not an admin who visits a Tabbycat site almost always wants to go to the public site for the tournament they are interested in.
3. Where a site hosts exactly one tournament, that tournament is almost always the tournament they are interested in. (The exception is if an admin wants to create a new tournament, which is a rare event.)
4. Where a site hosts multiple tournaments, there's no simple way to decide which is the one they actually care for. (Not strictly true—more on this later.)

Therefore, I think:
1. Admins:
    1. An admin visiting a site with exactly one tournament should be presented with the admin site for that tournament.
    2. An admin visiting a site with more than one tournament should be presented with a page to select a tournament. There's no good reason, in my view, for this page to include direct links to public sites—to me, that's just not a common use. But there's also no harm in including links to public sites. This page should include a link to create a new tournament, since that's a natural place to look.
    3. There should be a way to get from the admin site to the public site directly, preferably a link on which they can middle-click to just open the public site in a new tab. (I'd hold this regardless of whether there is a redirect from the home page.)
    4. There should be a way to create a new tournament from anywhere that would normally allow them to select a tournament. This includes the dropdown in the top-left of the admin page.
2. Public users:
    1. A public user visiting a site with exactly one tournament should be presented with the public site for that tournament.
    2. A public user visiting a site with more than one tournament should be presented with a page to select a tournament.

I haven't specified how this would work with URLs/redirects; there are probably multiple ways to achieve it.

I don't know what the "conceptual model" is, but if it that means the model used by developers to organise source code, I'm doubtful that that a useful model for the user. My point isn't so much about inconvenient clicks, as it is that there's a tendency for the home page to be a centre for the most common actions if it can be—particularly sites with login sessions. Sometimes that will match the most logical organisation of code, but sometimes it won't.

Maybe everything above is a poor conception of what users typically do, but basically I'd prefer a navigation model centred around users rather than around how developers conceptualise the site structure. To some extent we already do this—it's what you did with the left sidebar on the admin site, which is much easier to work with now than it was before.

[On multiple tournaments—this could be qualified, as follows: if exactly one tournament is currently in progress (and all others are past tournaments) it seems useful to direct users there, with some UI element to switch tournaments from every page. But I don't think implementing that is a high priority.]

**Comment by philipbelesky** [comment]
The conceptual model is the structure of the site in terms of how users understand how to navigate within it; nothing to do with code. For most sites this is most intuitive when it is hierarchical with vertical and horizontal moves within this hierarchy clearly sign posted (ie nav/sub navs)

The reason this issue posted was because someone was trying to get to the root page — but couldn't due to the way redirects work. The reason they were trying to get to the root page is because thats where they knew the add tournament button was. The reason they knew it was there is because thats where it is they ran through the setup process.

Having the add tournament button at that root level is kind of required when initially setting up the site, but it also makes sense when tournaments are already established — a tournament is the first major choice one must make in navigating a site, and whenever there is a list of objects the option to create a new object is usually presented.

To the extent redirects add convenience they do so at the cost of user confusion. For public users this doesn't matter as much as the redirect/non-redirect options will always mirror their desires — they will always want to choose a tournament or not have any option. For admin users we can't assume that intent because they always have multiple choices whether or not there are multiple tournaments. 

Adding extra links within the admin site to create new tournaments or switch to public pages is unnecessary given we already have a page that allows people to get to access those things, we have already taught them to use it, and its position in the navigation hierarchy makes sense. Links within the admin page can serve as conveniences of a sort but at the point they are in a dropdown they (a) can't be assumed to be discoverable and (b) shouldn't replace the original navigation method as that would lead to even more confusion. 

Anyway, suggestions:

- Making admin users click an extra time is totally worth it if it prevents confusion in how users understand how to navigate that site
- Even if a redirect is in place admin users should always have a clear method to return to the root page for the purposes of switching tournaments and adding new ones
- Am ambivalent about adding extra nav options to the admin area, but to the extent the tournament's name is a dropdown it should match the actions available on the root page and their order.

**Comment by czlee** [comment]
Okay, I understand the concern about consistency. It seems to me then that the "create new tournament" button is misplaced (my fault, I wasn't really thinking that hard when I put it there). The setup process shouldn't really take them through the root page, it should just take them directly to create a new tournament as soon as they've created the first account. I mean, there's nothing else to do.

In my mind the site would work analogously to being signed into multiple accounts in Gmail. On occasion, when it can't figure out what else to do, it might take you to a page from which you need to select which account you want. But that's meant to be an "intermediate page" only. In general use, the way to switch accounts is to use the dropdown in the top right (for us, top left). I admit that to do this properly, I guess we'd need a session cookie to remember the last tournament selection.

So my proposal is to reduce what we currently call the "root page" to a last-resort intermediate page, and to make the primary means of switching tournaments—and creating new ones—through a dropdown, or another UI element that just opens a menu. I appreciate that the element might need some sort of useful symbol on it.

Would that be a bad idea? I feel like it would address both convenience and conceptual concerns, but maybe there's something about the multiple-tournament use-case that I don't understand such that the accounts analogy doesn't work(?)

**Comment by philipbelesky** [comment]
I don't think its necessary misplaced — as I mentioned earlier its the only obvious place where a list of tournaments is shown, and so its probably the best place for actions that affect that list.

The multiple accounts thing works in that its a a horizontal traversal between sections of content, but becomes confusing when that is the only way to make the change. Again, the on-boarding process uses that root page, and in multiple tournament settings the root page is shown before admin users login. It's not going anywhere, thus it should be consistently available (as the user I mentioned expected it to be). As a side note I wish google actually did ask me which account I wanted to use before proceeding in many circumstances, such is the joy of managing files and documents across ~4 google documents accounts. 

In terms of implementation adding the extra items to be current drop down is fine. I still think either the redirect should be disabled for admins or at the least there should be a view that allows them to access the page without being redirected. But then even that is a source of potential confusion.

**Comment by czlee** [comment]
Okay. Happy to run with abolishing the redirect for admins, I'll complain again later if I continue to find it troublesome after a couple of months. Would like it to remain in place for public sites if you don't mind that.
