### ISSUE TITLE
Adjudicator Allocation Page should indicate a room's liveness

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#323]
I'm going to split off some of the more complex parts of the adj-allocation page for seperate issues for additional context and feedback. First part up is a Debate-Breaker style highlighting of live rooms, per break-category. Current plan is to show this by highlighting the Wins column Green/Yellow/Red with some indication of break category.

Unclear how complicated the algorithm is to determine liveness. @czlee let me know if you were interesting in doing it and I can wire up the front end to a dummy function.

**Comment by czlee** [comment]
I'd be interested in doing it. This would be much, much simpler than it was for BP. The hard part is more definition than algorithms: what does it mean for a room to be live? Different people have different definitions of this, too.

A simple ternary basis (safe/live/dead) would be simplest, where "**safe**" means "it's not possible for either team not to break", "**dead**" means "it's not possible for either team to break", and "**live**" means "there exists at least one scenario where the team would break, and at least one where the team would not". This is what I'd advocate in the first instance, and I think it'd be straightforward enough to be tractable, while still (if we do it properly*) hard enough to be challenging.

But a lot of people want to allow for differentiation between different "levels" of "liveness", which is where definitions become tricky. I've hard it advocated that liveness be measured by the "probability" that they'll break. Since this requires some prior on how likely a team is to win a debate, I'm not sure what that means. Also, some people advocate for speaks to be taken into account; but the same problem applies: if we can just guess that a team won't hit straight 79s for the remainder of the competition, then what are their odds of getting straight 77s?

For Adjumo we did a rough notion of "maximally live" meaning "it would be live if this round were the last round". This was a quick, easy way to differentiate between teams in the middle of the bubble and those at the edge, but it's not clear that there's good reason to treat liveness this way. Also, some judges I've talked to think that teams at the _bottom_ of the bubble should get priority, because their debate is the do-or-die debate.

Like feedback, it's one of those things where adjudication cores can reasonably disagree, so we should think about how to make this usefully flexible.

* by "properly" I mean "taking into account _all_ current standings". So, for example, while it might be true that you need 5 wins to have a chance before the competition, in edge cases it might be that after 4 rounds, results have made it so that 6 wins are necessary.

**Comment by philipbelesky** [comment]
Slight updates

- [X] As far as I know the calculation is performing correctly for the open beak categories
- [ ] As far as I know the calculation is not performing correctly for non-general beak categories

There's also an open question on how this number should be presented in the interface. Currently its a range from 0-2, with +1 being added if a team is 'live' for any category

**Comment by philipbelesky** [comment]
I don't remember any outright bugs with this; closing as I think its in a minimal-viable state. #347 supersedes this issue for specific enhancements / edge cases.
