### ISSUE TITLE
Active/Inactive Teams

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#34]
At an upcoming tournament, there will be a number of teams that arrive and debate for 2 rounds on the sunday, but weren't around for the first 4 rounds on the Saturday. Am I right in thinking that if I add the Sunday-only teams in as Teams from the get-go, but leave them marked as Inactive until the 5th round that they will appear in the draw on 0 wins? Has the software been tested for this before?

Over the weekend I'll do the data entry required to fully test this, but though it would be good to ask and see if this has come up before / gauge any potential issues.

**Comment by czlee** [comment]
I just tried this again (leaving four teams out in round 1, then generating round 2) and it didn't crash. Teams with no debates rank last on the draw with all metrics as zero (because the standings generator querysets would return `None`, which the generator then converts to a 0); the absent teams then cluster at the bottom of the draw.

In particular this means their speaks will be zero, not the minimum possible. I don't really have a problem with this, mainly because building in the requisite infrastructure to support choosing the penalty would be nontrivial. But it's worth noting that, because `TeamScore` requires a debate-team in our schema, if someone wanted to assign a nonzero speaker score to absent teams by editing the database, they'd basically have to create a ghost/bye debate for the purpose.

This doesn't really bother me, but wanted to check with you, @philipbelesky?

**Comment by philipbelesky** [comment]
I think thats the expected or at least acceptable behaviour.
