### ISSUE TITLE
Add division-specific points metric

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#348]
For context: at the moment WADL's division standings metrics are Points > Who Beat Whom > Average Winning Margin > Average Speaks. 

However, the initial sorting by points is incorrect in some tournaments, wherein the  — what matters is not points in the absolute sense, but that a team had the highest points within their division (ie did they win the division). So at the moment the overall ranks have some teams with a division rank of 2 placed above those with a division rank of 1. 

Fixing this by adding a metric that adds a 1/0 metric score depending on whether a team has the highest number of points in its division.

**Comment by philipbelesky** [comment]
Hmm, actually this is slightly more difficult as just gauging the highest number of points isn't enough: if there can only be one division winner it needs take into account WBW/AWM/ASS also to produce a single outcome — ie basically do everything the current division rank does.

However this form of division rank wouldn't start counting past 1; once all the division winners have been identified the next eligible break spots aren't determined by division ranks but by their Points/WBW/AWM/ASS across all divisions. 

At the moment I'm leaning towards keeping the existing structure for everything else (rather than trying to rework division ranks to also be a metric, as its useful as-is) and instead building a `DivisionsWinnerMetricAnnotator` that has the sole function of finding the teams with highest points and then resolving ties as needed (rather than pulling down all the info for all teams as in `DivisionsWhoBeatWhomMetricAnnotator`. It can probably reuse some functions in the other annotators to reduce overlap though. The new function essentially would return a 0/1 as the first metric and the remaining metrics would work as is and stay in place (to resolve ties amongst the wildcard teams that weren't division winners). 

Thoughts @czlee ?

**Comment by czlee** [comment]
I'm a little confused about how ranking is supposed to work. Is this understanding correct, if there are _d_ divisions and _T_ teams in total:

- The 1st through _d_th ranked teams are all division winners.
- Within the division winners, they are sorted by points, then margin, then speaks, even though none of them competed against each other.
- The _d+1_th through _T_th teams are all teams who did not win their division, sorted by points, then margin, then speaks.
- For every team that did not win their division, their ranking within their division is immaterial.

If so then I agree that this is nontrivial, since the current standings generators assume that all metrics are annotated before all rankings are. Though I suspect the `DivisionWinnerMetricAnnotator` idea is probably the easiest in practice, we would then just make that annotator as complex as it needs to be to do its job. I guess we might be tempted to abstract it so that it's not hard-coded to go points-wbw-margin-speaks, so that any subgroup-winner metric can be made easily, but unless we foresee other use-cases for this, I'm tempted to cross that bridge when it comes, since it's not clear conceptually how to make this idea coherent.

**Comment by philipbelesky** [comment]
I'm waiting on confirmation of some details but my broad understanding is:

- For Junior/Novice leagues division winners are irrelevant, its a clean top break based on Points>WBW>Margin>Speaks
- For Senior leagues the top X are always division winners, determined by MostPointsInDivision with WBW breaking ties. Presumably ranking within this set proceeds by Points > Margin > Speaks. Those who did not win the division are then ranked via a global ranking of Points > WBW > Margin > Speaks.

So yea that matches what you've outlined above if I'm not mistaken. If `DivisionWinnerMetricAnnotator` can break ties with WBW (and I guess margins/speaks for extreme edge cases) then I assume the rankings should be correct with the following settings: DivisionWinner > DivisionPoints > WBW > Margin > Speaks. So `DivisionWinnerMetricAnnotator ` will end up being a messy class, but given the rarity of its use I don't think its worth trying to refactor other things around it.

**Comment by czlee** [comment]
Actually, possibly silly question: Is this actually how teams are ranked for general purposes, or is this just for the purposes of the break? In other words, is there a chance this is more appropriately written as a break qualification method, analogously to AIDA pre-2015 and 2016?

Of course this might be a moot question, since breakqual relies on standings. But just a thought, if to some extent the idea is to "adjust" the "true" standings to achieve some goal in the break.

**Comment by philipbelesky** [comment]
Afaik there isn't any need for a general purpose ranking distinct to break rankings, given the in rounds are all round robin. So it could be a breakqual method, although it may be easier from a code structuring point (can share methods) and user perspective (easier to configure) if its kept as a ranking method.

**Comment by czlee** [comment]
Yeah, it's not obvious which would be easier, but I was thinking that as a break qualification method, we would generate standings as usual with division rank (and existing metrics), then the break generation would:
- first, run through the standings and take every team with division rank 1, in the order they appear in the standings,
- then, run a second pass through the standings and take the top _b_ − _d_ teams remaining, where _b_ is the break size and _d_ is the number of divisions.

This would allow us to avoid contorting the standings metrics with multiple layers to account for this. Since `break_rank` is already distinct from `rank`, the mismatch between standings and break rank shouldn't, in terms of technical functionality, present a problem. The question I'm not sure about is whether this mismatch would be acceptable to WADL?

**Comment by philipbelesky** [comment]
Ah, of course, having access to division rank then would make it much easier to change the ordering. I don't think WADL would mind if the standings page is 'inaccurate' for one of the leagues as long as the break page is correct — this is all instrumental to just creating a draw for the foctos/octos.

**Comment by czlee** [comment]
Does this need to be Devon Rex? I can just do it as part of #307 and bump the priority of that one up a bit.

**Comment by philipbelesky** [comment]
No, WADL is still on develop branches so there's nothing tying this to any
release milestone. I was going to do it sometime this coming week to
properly wrap up the WADL spec for this year though. If you wanted to do it
as part of #307 what would the rough timeframe be?

**Comment by czlee** [comment]
If I bump it up to top priority, maybe a week or two? Possibly sooner depending on how bored I get over the next four days.

**Comment by philipbelesky** [comment]
Slight update here: for novice/junior breaks its actually more complicated. Division winners there are also guaranteed to break, with the top non-division-winning teams filling up the remaining break spots. However, once these spots have been determined, the rankings within them are clean. IE once the 16 break spots have been filled by teams, the ranking within those spots reverts back to Points > Margin > Speaks regardless of whether they were a division winner or not. This is at least partly because there are no partial elimination rounds for those levels.

**Comment by czlee** [comment]
To me this is actually slightly simpler and more logical, I was gonna ask why they don't keep ranks clean lol. So there are two distinct break qualification rules for WADL, one for novice/junior that keeps ranks clean, and one for senior that promotes division winners to the top?

**Comment by philipbelesky** [comment]
Yup!

**Comment by czlee** [comment]
@philipbelesky Do you want to have a look at develop (post-645d0d6) and see if it meets what you want? (I haven't tested it, except to sanity-check it on a dataset that doesn't even have divisions. If you have an appropriate dataset that'd be useful?)

**Comment by philipbelesky** [comment]
It looks good across each level, I've just sent off to ask them to check it (there are some discrepancies in one level but the rankings look logical). I've added a data dump from the live site to the datasets repo also.

**Comment by czlee** [comment]
Cool. I'm probably not going to write unit tests for it, I think the breakqual module is both low-priority and complicated enough not to deserve unit test attention unless I get bored one day. Is this good to close then, or do you want to wait to hear back from them?

**Comment by philipbelesky** [comment]
Still haven't heard back, but any changes are not require until next year I think so closing for now.
