### ISSUE TITLE
Improve error handling in visual importer

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#394]
The current visual importer seems to be prone to user error. Rough ideas for how to fix:

1. For institutions and venues, reroute through the data importer framework, possibly writing a new importer.
2. For teams and adjudicators, have the front-end assemble a CSV string with the information provided, then reroute through the data import framework, probably writing a new importer.
3. The importer will return a bunch of errors on failure, of course; the GUI needs to be able to show them intelligently.

**Comment by philipbelesky** [comment]
Quick note: looking back at many of the importer bugs that have come up, shifting to running things through the standard importer wouldn't have avoided them. In most cases it's a result of bad input going into the `textareas` or a mishandling of how to translate from long strings into structured data. At the point its possible to assemble a CSV string to run through the importer most of the bugs that have come up would already have been caught.

**Comment by czlee** [comment]
The whole point of the standard importer was to robustly handle bad input and return a list of useful error messages. Long strings should be caught by the standard importer, and if they're not, that's a bug in the standard importer (because it would also affect imports done via the management command). The views shouldn't have to do any data sanitisation at all, and for them to do so violates DRY. The job of the view should just be to pass input into the importer, and show the user and resulting errors, not to try and assemble a CSV string that pre-empts all user error.

Or, more precisely, the only user errors that it should try to pick up on are ones that would cause the CSV string itself to be a malformed CSV string (independent of content). But assuming we're assembling it using a CSV library (that automatically escapes characters as necessary), this should involve the view doing precisely nothing, too.

**Comment by czlee** [comment]
To give an analogy: When in other contexts we use (say) a model form (_e.g._ the create tournament page), the view doesn't do any error checking on the data at all. Responsibility for that is left to the form class, which in turn delegates a lot of it to the fields in the model. That's because the understanding of what constitutes "good" or "bad" input lies best with the code that defines it—the model.

Similarly, the base data importer delegates as much error checking as it can to the models, does on top whatever error checking it absolutely cannot delegate (_e.g._ duplicate entries), and (like forms) manages a collection of errors that may arise from bad user input. As with model forms, this understanding of what's "good" and "bad" input shouldn't be duplicated in the views.

**Comment by philipbelesky** [comment]
The problem is though for the visual importer to be convenient to use it needs to offer the user a different input mechanism. For the normal importer the data interface is a csv file. For the visual importer that is a `textarea` and/or structured `inputs`. These different interface result is different types of bad data than the the csv-like string structure that the standard importer is setup to handle. Hence as I said, most of the edge cases the visual importer handles may proceed the concerns of the standard importer, or are things it doesn't account for.

For example something I fixed earlier was users copy/pasting in a list of venues without priorities. This has happened at least two different tournaments. If the textarea string had been passed straight to the standard importer it also would have crashed — it expects all venues to have priorities. However, by catching that problem in the view, we can then, in the subsequent view (when they are confirming the data as fields) provide a default pre-set priority field for all venues. This behaviour would not be desirable in the standard importer because it is designed to run once and shouldn't really fill in data on the user's behalf. The visual importer can happily do this because it asks for confirmation.

DRY for web forms has always been a bit of a cluster fuck; ditto for views. But certainly in this case there is a need for different sanitisation methods once we accept different input methods. In many cases I agree we can shift what is currently handled by the view into the standard importer (ie long names) but I don't think it will cover all cases.

**Comment by czlee** [comment]
I don't understand the distinction between a `textarea` that asks users to input CSV, and a CSV file. They're processed in the same way, and provide the same precision of response. CSV files literally allow any arbitrary string, so I'm pretty sure that there is no user error that can happen in a user form, that cannot happen in a CSV file.

If there should be no expectation that all venues have priorities, that _is_ a problem with the model. The correct fix is just to add `default=10` (or something) to the `Venue` model. That's literally the only change that should have been necessary for the importer to be able to handle venues without priorities. The standard data importer itself is already perfectly capable of handling missing fields, either missing from the file outright or left blank in the CSV string, provided a default exists in the model: it just leaves it to the model to handle as the model is supposed to. This was, too, part of the whole point of the data importer class.

So I disagree that it's not desirable for the standard importer to fill in data on the user's behalf. I'd say that _anything_ where there is a sensible default should just have it specified in the model, because that's what defaults are for. If the view should check with the user in certain circumstances to be sure, that's fine, but that's not the same thing as the view actually filling in defaults.

That being the case, I still can't see why you'd need different sanitisation methods. The set of user errors possible in a web form is a strict subset of the set of user errors possible in an arbitrary string, because you can always put those errors into the CSV string.

The only difference I can think of is, where you have a lot of text boxes (not a single text area), a good form would route error messages towards particular text fields ("This name is too long"), rather than just providing a list at the top of the page ("The name of the 7th team is too long"). In that case, the CSV importer shouldn't be used, and an extension of Django's [model forms](https://docs.djangoproject.com/en/1.10/topics/forms/modelforms/) should be used instead, because they already incorporate data validation. (That still doesn't violate DRY, because the standard importer pushes as much validation as it can to the model.)

**Comment by czlee** [comment]
Scratch that—I stand by some of the above not all of it, will think through a bit more and comment again once I have something more concrete. Rejigging the visual importer architecture may as well involve migrating it to class-based views, so not a priority for 1.2.

**Comment by czlee** [comment]
Closing this in favor of a new issue specifically for migrating the visual importer to class-based views, since that'll be a bit more involved.
