### ISSUE TITLE
Merge VenueGroup and VenueConstraintCategory

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#427]
To me it seems more intuitive to have a single classification system for signifying the attributes of rooms, whether for display purposes or constraint/assignment purposes. It also reduces data entry loads when those two purposes coincide. Rough plan:

- [x] Merge the models into a new model (`VenueCategory`?)
- [x] Assign attributes to this new model to control the visual display
    - [x] Probably some sort of `display` toggle that switches between None/Prefix/Suffix
    - [x] Update table views to use this prefix/suffix. Additional toggles may be needed to specify whether things get a column to themselves or not
    - [x] Add admin-only tooltips that display all this information all the tme
- [x] Create a migration that ideally carries forward the data
- [x] Create a visual importer page for adding and assigning VenueCategories (think a big matrix/table with checkboxes)

**Comment by czlee** [comment]
I'll do the model and migration in one commit, I've been trying (and not always succeeding) to do them so that migrations match models in every commit. New model plan, roughly:

```
class VenueCategory:
    name = CharField()
    short_name = CharField()
    team_capacity = IntegerField(null=True)
    venues = ManyToManyField(Venue)

    display_in_venue_name = CharField(choices=('-','P','S'))
    display_in_tooltip = BooleanField()
```

What would prefixes and suffixes look like?

**Comment by philipbelesky** [comment]
`team_capacity` I'm trying to deprecate in favour of just counting the `venues`. If you think it serves a valid non-WADL use we can keep it around though. 

Is `display_in_tooltip` just for admins? 

At a basic level prefixes/suffixes would just be arbitrary text strings (probably using `short_name`) that get joined into the venue name. At a more advanced level there could be the ability to indicate whether a `VenueCategory` should get its own column (to make sorting easier).

**Comment by czlee** [comment]
`team_capacity`: Nah, can deprecate then.

`display_in_tooltip`: Actually, I intended it for the public interface. For when you want to make the information about accessibility accessible (ha!), but didn't want to scream it next to venue names themselves ("Green - B05 Step-Free")

**Comment by czlee** [comment]
Proposed model:

``` python
class VenueCategory(models.Model):
    """Represents a category of venues, typically used for (physical real-world)
    navigation aid, division allocations and/or venue constraints."""

    DISPLAY_NONE = '-'
    DISPLAY_PREFIX = 'P'
    DISPLAY_SUFFIX = 'S'
    DISPLAY_IN_VENUE_NAME_CHOICES = ((DISPLAY_NONE, _("Don't display in venue name")),
                                     (DISPLAY_PREFIX, _("Display as prefix")),
                                     (DISPLAY_SUFFIX, _("Display as suffix")))

    name = models.CharField(unique=True, max_length=200,
        verbose_name=_("name"),
        help_text=_("Name of category, e.g., \"Purple\", \"Step-free access\", "
            "\"Close to tab room\""))
    short_name = models.CharField(max_length=25, blank=True,
        verbose_name=_("short_name"),
        help_text=_("Short name, e.g., \"Purple\". This name is shown when the category is "
            "prefixed or suffixed to a venue name in the draw, e.g., \"Purple – G05\"."))
    description = models.CharField(max_length=200, blank=True,
        verbose_name=_("description"),
        help_text=_("Description, as the predicate of a sentence, e.g. \"has step-free access\", "
            "\"is close to the briefing hall\". This description follows \"This venue\" when "
            "shown in tooltips, e.g., \"This venue is close to the briefing hall.\"."))

    venues = models.ManyToManyField(Venue, verbose_name=_("venues"))

    display_in_venue_name = models.CharField(max_length=1, choices=DISPLAY_IN_VENUE_NAME_CHOICES,
        verbose_name=_("display in venue name"),
        help_text=_("Prefix: \"Purple – G05\", Suffix: \"G05 – Purple\""))
    display_in_tooltip = models.BooleanField(
        verbose_name=_("display in tooltip"),
        help_text=_("Displays the description in the tooltip for the venue."))
```

I added a `description` field. In my head, for the kind of thing you'd put in a tooltip (rather than broadcast in the GA draw), it's probably more of an explanation, like, "This venue has step-free access, is close to general assembly and has movable seating," rather than "Categories: Step-free, Close to GA, Movable seating".

Neither short name nor description are mandatory (_i.e._ they can both take empty strings). That said, I suppose I'm not really sure what `name` would be used for, so I'm open to ditching it and then renaming `short_name` to `name` and making it mandatory.

Thoughts?

**Comment by philipbelesky** [comment]
Agree that having just a `name` and a `description` makes sense — description can be as verbose as needed so can pick up any slack. That said the tooltips are probably mostly for admins — on mobile devices they aren't very discoverable. They might also actually be suppressed on the draw pages (so they don't popover during scrolls). Maybe I'll fix that (once this is completed and venues have tooltips):

- [ ] Once venue category popovers are implemented change public draw pages so that popovers are only disabled *once scrolling has commenced*

**Comment by czlee** [comment]
Question, why do we have the autoscroll available on public draw pages? Shouldn't it just be for the GA view (the one in admin where you go from "display draw by team/venue")?

In my imagination, for those teams with accessibility requirements we would tell them specifically (at large tournaments that we run) that they can check that venues are step-free (or whatever attribute) by clicking on the venue name in the draw. So for this use-case I think it's not disastrous if they're not very discoverable for most people, since most people won't care. I agree that admins will in practice use them more often, though I think for admins we'd just always show the description if it exists, irrespective of whether that field is checked.

If we wanted to be _really_ fancy we could also add a field to each venue where organisers could (optionally) specify a direct link to a map (like, a permalink on Google Maps, or just a collection of images hosted somewhere else), which would also appear in a venue tooltip. But that's another idea…

**Comment by philipbelesky** [comment]
So the thinking on having the scrolling there it means assistants or logged out admins can do a draw release publicly (ie the round has been release) so it has value as a fallback option. That said I can't recall if an actual use case prompted this. 

- [ ] Check if scrollers are hidden on mobile devices

**Comment by czlee** [comment]
@philipbelesky I've put the new model and associated migrations in place, but haven't removed the old models. The next step is to replace 

Because the "primary group" of a venue is no longer a field, there are some things we can no longer do, mainly operations at the database level. For example:

- You can't sort by `['group', 'name']`, because you can't sort by group.
- Constructing the name is nontrivial, because the venue categories for a venue aren't just an attribute. I've written `Venue.display_name` to construct prefixes/suffixes appropriately, which might be useful.
- Note that calling the display name calls `venuecategory_set`, which triggers a database query. To avoid this, queries that retrieve venues should use `.prefetch_related('venuecategory_set')`, which will trigger just one extra database query to fetch all venue category information, rather than a database query for every venue individually.
    - Because it no longer uses a `ForeignKey`, `select_related()` is no longer an option, and at least one extra database query is unavoidable. I don't think this is too much of a concern though, an extra db query doesn't tend to kill things, but an extra db query _per venue_ does.
    - Nevertheless, because this _does_ trigger an extra db query, I'm reluctant to add it to `VenueManager.get_queryset()`, because then there's no way to opt out of it when it's not necessary. We'll just need to prefetch `venuecategory_set` wherever appropriate. (Putting it in `debateset_with_prefetches` will help with this.)

Can you fix the venue rendering in utils/tables.py so that it doesn't use groups?

**Comment by philipbelesky** [comment]
Sure, happy to fix the rendering, it might need to wait until the weekend though.

**Comment by czlee** [comment]
Sure, whenever convenient. I think I've finished all the model changes and migrations (including for divisions), but, probably about five or so views are broken now, and I think they're all views that you're more familiar with than I am. Let me know if I missed a spot.

A note on the division migration: I wanted to keep the division migration within the division app, so rather than converting `division.venue_group` to `division.venue_category` straight away, it does it in a separate migration (from the one that converts `VenueGroup` to `VenueCategory`. This means that the mapping might, in very odd cases, not be perfect, since it tries to identify the correct `VenueCategory` for each `VenueGroup` by matching their names. To avoid the risk of migrations failing in corner cases, I got it just to set the category to `None` if it can't figure out which category to use quickly, so in some rare cases this might entail data loss.

**Comment by czlee** [comment]
- [ ] Remove deprecated models (once all other code migration is done)

**Comment by philipbelesky** [comment]
Hmm this is relatively extensive:

- [ ] Update the way venues are constructed in tables.py to use venue prefix/suffixes. However in doing so, `enable_venue_groups` as a preference doesn't make sense. For WADL's purposes they basically just want the venue category name so this should probably be changed to reflect that, a `hide_individual_venue`s or something that just shows the categories in the draw
- [ ] The importer needs to be changed to use categories rather than groups. If we want to be fancy we could interpret all comma separated strings after the venue as categories, or just one.
- [ ] `team_record.html` needs to be updated also. In conjunction with the table change, there should probably be a method on `Venue` that correctly formats its name so it can be used everywhere.
- [ ] both forms of printable ballots need need to switch to use the above method
- [ ] as does `ballot_checkin.html`
- [ ] as does `public_add_ballot.html`
- [ ] `DivisionAllocator` will need some non trivial changes

**Comment by philipbelesky** [comment]
@czlee are all your changes for this pushed up? I couldn't find a `display_name` in `Venue`.

**Comment by czlee** [comment]
Ha, I warned you changing to this model structure would derail a lot of code 😛

Yep, everything should be pushed! There isn't a `display_name`, I thought we were running with just `name` and `description`? Then `name` should be used as prefix/suffix, and `description` should be used in sentences?

**Comment by czlee** [comment]
Wait, sorry, I'm talking nonsense/forgot what I did.

`display_name` is a property of `Venue`, not `VenueCategory`, and it's the method on `Venue` that correctly formats its name so it can be used everywhere. Don't forget to `.prefetch_related('venuecategory_set')`.

- [Relevant lines in venues/models.py on feature/#427-venuecategory](https://github.com/czlee/tabbycat/blob/feature/%23427-venuecategory/tabbycat/venues/models.py#L46-L64)
- [Permalink to same lines referenced by commit hash `dd85977`](https://github.com/czlee/tabbycat/blob/dd85977118d14ebcc3eeccc03effdb36e20b5b38/tabbycat/venues/models.py#L46-L64)

**Comment by philipbelesky** [comment]
Ok so everything is roughly done apart from the new popovers and the migrations. For migrations should they just be made as usual? Or do we need to do something special on account of the custom migration you wrote earlier?

**Comment by czlee** [comment]
I think (or hope) I did all the necessary custom migrations, so just removing the final models should be just as usual, nothing special :smiley:
