### ISSUE TITLE
Add default set of feedback questions to newly create Tournaments

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#430]
Setting up feedback questions can be somewhat time consuming. It is also unclear to novice users how to go about this per-se — it might not be immediately clear that what the backend/online/printable feedback submission methods have is configurable. 

We could certainly improve the prompting to use understand and set configurable questions. But I think that there is also value in having a 'default' set of generic questions in addition to the basic rating scale — such as 'Comments' and 'Do You Agree' etc. 

Adding these in would offer a much better out-of-the-box experience where small/medium sized tournaments (who otherwise wouldn't bother) can just roll with what we give them for their (limited) feedback needs. It will probably also help surface the configurability of the questions themselves — users can see how the objects in the database area matchup to existing questions.

I'm not sure about how to actually implement this but I assume there is some hook on to when a `Tournament` is created that we can manually create a couple of questions. Open to alternate methods/options also.

**Comment by czlee** [comment]
I'd worry about our default questions having the effort of setting norms on the circuit, so while I think default questions wouldn't be a bad idea, I'd want to keep them absolutely minimal, to a set of questions that is already universal and wholly uncontroversial, even to the extent that they should nudge adj cores of small tournaments into instinctively wanting to add one or two questions themselves. I can think of just two questions that fit this category, basically the two that you mentioned:

1. Did you agree with this adjudicator's decision?
2. Comments

I think we should just put it in the `TournamentForm` in `tournaments/forms.py`, perhaps abstracting to a function in `tournaments/utils.py`? It would only be generated for tournaments created through the form in the UI, but I think that a sensible restriction.

**Comment by philipbelesky** [comment]
Hmm, I think a "Should this adjudicator be promoted or demoted?" is arguably common enough to include (and is often useful to cross check against the score rating given). Having a question or two that people may want to delete is also a good way to nudge people into editing the questions themselves?

Sounds good RE: putting it into the tournament form. Any objection if this gets merged into 1.2.1 along with the other printing 'fixes'?

**Comment by czlee** [comment]
I've only seen that question at Australs, and Malaysia and Thessaloniki WUDC, so I'm not so sure about that. Perhaps it's common on the Australian circuit, but it's rare in North America, and there are reasonable arguments against asking it. If I thought people would be nudged into editing questions then I'd consider that effect, but insofar as we're doing this for inexperienced adj cores, I think it's more likely that what we set will just become the norm on the circuit. I'd rather avoid anything that might have that effect—or insofar as we must set a "default norm" (which I accept we can't avoid), I'd rather that it be so bland that the nudge is towards adding, not removing, questions, and so that those who don't really care get existent but not detailed information.

In fact, I'm even half-hearted about the "did you agree?" question.

Since this is a new feature, unless there's a particular urgency to it, I'd really rather that it be kept on develop until Genetta?

**Comment by philipbelesky** [comment]
Ok, I think in the meantime I'll just add alerts to the printing pages that point out when questions aer not configured. I might also add the default scale to that forms just so they show something. 

My thinking for Genetta was largely to try and minimise the number of new features to try and reduce the chances for regressions on all the front-end updates. But this should have minimal chance of affecting those.

**Comment by czlee** [comment]
:+1: on alerts. All feedback has a score scale by default, doesn't it? I thought we never abstracted scores?
https://github.com/czlee/tabbycat/blob/develop/tabbycat/adjfeedback/forms.py#L178
(In other words, that's not a default question to insert in the database, right?)

**Comment by philipbelesky** [comment]
No it's not a default question, but currently the printed forms don't show it — only any custom questions.
