### ISSUE TITLE
Investigate convenience feature to aid 'iron person' data entry

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#431]
So I'm thinking of this as primarily a front-end change with minimal backend effects. Basically it would add some checkboxes to the front end that indicate that the speaker is speaking twice, at which point the form would allow people to be double-selected. I'm imagining when submitting this would also automatically create a new *Person Name (ironperson)* `Speaker` and assign them the lower of the two scores. 

How this works with in subsequent data entry could be complicated. Either we can stick with showing the duplicate speakers in the dropdown approach. However thats probably confusing as there are now two ways to accomplish the same thing. Alternately we could add a small boolean field to all speakers like `ironperson` that then filters them out from the list of dropdown options. 

Shifting away from the 'primarily a front-end change' there could also be a subclass of `Speaker` like `ShadowSpeaker` that is identical but with a foreign key to the original speaker. That probably has a higher risk though of breaking existing implementations. 

So the intent here is both to streamline data entry (this seems like a common enough scenario that currently you need indepth knowledge to solve) and to a certain extent standardise the way in which these duplicate speakers are made (at least until/if) we implement better backend solution.

**Comment by czlee** [comment]
Just thinking about models:

Currently, there's no _database_ restriction on a speaker speaking twice in a debate, or more precisely, there is no uniqueness constraint on the `speaker` field in `SpeakerScore`. The only uniqueness constraint is this:
``` python
class SpeakerScore(models.Model):
    # ...
    class Meta:
        unique_together = [('debate_team', 'position', 'ballot_submission')]
``` 
In fact, there can't be a uniqueness constraint on speaker identity: a speaker has to be able to speak twice for reply speeches to work. So at face, there's no model-level reason why the form _can't_ allow speakers to speak in two substantive speeches. We just designed the form to prevent it, because that's normally a data entry error.

But then, what would it _break_ if we just allowed speakers to speak twice? The only two things I can think of are on the speaker tab: (a) speaker averages would now count "ironman" speeches, and (b) the speaker score relating to a speaker in any given debate would no longer be unique. With the current implementation, this wouldn't actually cause the tab to crash, just be incorrect: in (a) it would just be summing/averaging the wrong data; in (b), the score appearing on the tab would be whichever happens to appear last in the query result.

In either case, we could account for this by just adding a `BooleanField` to the relevant `SpeakerScore` object (as opposed to creating a new `Speaker`), and filtering for that in those scenarios. Rather than calling it `ironperson`, we could even just describe it for what it is: "exclude from statistics" or "exclude from tab" or just `exclude` or something.

Finally: `SpeakerScoreByAdj` isn't affected, because it stores scores by position, not by speaker identity.

What do you think? Is there anything other than (a) and (b) that just allowing the iron-score to be saved as-is, without any additional models or fields, would break?

**Comment by philipbelesky** [comment]
Yea, not having to create duplicate `Speakers` just for this purpose sounds ideal, and to an extent any side effects for speaker averages and the like are less worrisome than having the actual result be compromised. At that point attaching it to the `SpeakerScore` sounds more preferrable.

**Comment by czlee** [comment]
I did the model and speaker tab part on the new `feature/#431-ironperson` branch.

**Comment by czlee** [comment]
How do we want to do the forms? The naïve thing to do would be to add a "ghost" checkbox for each speaker on the ballot form, and have users check the ones they want to ghost out. But that might be too much clutter? Another way would be to add options to disable duplicate speaker checks (either for the whole debate or with lower granularity), and have `BallotSetForm` figure out what to ghost out (_i.e._ the lower score)? Did you have a vision for this?

**Comment by philipbelesky** [comment]
Hmm I was planning on trying a few things. The initial thought was to try and hide this as much as possible — perhaps just having a per-team checkbox somewhere asking if there were any repeat/iron person speakers. Once that is enabled duplicate checks could be disable for the existing drop downs, or perhaps a per-person checkbox would disable the check just for that particular checkbox.

**Comment by philipbelesky** [comment]
Progress/path to merging:

- [X] Implement set/get/save methods in `BallotSet`
- [X] Correctly disable validation checks for non unique speakers
- [ ] Filter ghost speeches from the speaker tab rankings
- [ ] Properly implement tab indexing
- [ ] Write new documentation

@czlee you probably want to check my implementations on the first two at your leisure

**Comment by philipbelesky** [comment]
Just a heads up: have merged this into develop.

**Comment by philipbelesky** [comment]
Closing as this seems to have worked successfully at Easters (just went in and checked a few people's speaks are showing up as the non-ghost value).
