### ISSUE TITLE
New importer does not assign emoji to teams

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#450]
This is clearly a travesty. I might go through and add a management command to regenerate them; if just because the Easters teams have now all been imported emoji-less.

**Comment by czlee** [comment]
Wait, did the old visual importer assign emoji?

The best thing to do is probably to move the emoji methods of the tournament data importer to a new file, and then call that from everywhere relevant:
https://github.com/czlee/tabbycat/blob/develop/tabbycat/importer/base.py#L305-L330

It might take some thinking to write it in a way that integrates well everywhere it needs to. Currently it's set up to integrate into the base importer, which looking at it again probably isn't the best way. Actually, it should really just be a function that bulk-assigns emoji to all teams in a given queryset, which is run after each batch of teams is created/imported.

**Comment by philipbelesky** [comment]
I wonder if it would be easier to just assign it to a post-creation hook on the `Team` model itself? It seems universally useful to have it generated whenever a team is created given there is that UI preference to turn it on or off.

**Comment by czlee** [comment]
Possibly. We could go one better, actually: we could set `Team.emoji`'s `default` to a callable, which is then called every time a new `Team` is created. The catch is that the callable can't take any arguments, which has hamstrung me in the past, but I think for this one it's okay. We just have to write the callable to query the database for emoji currently in use, to avoid duplicates.

The main problem with this is performance: If you bulk-create teams, you have to launch an SQL query to check what emoji are already taken with every team you create. This isn't ideal, but I think since creating teams doesn't happen every often (and bulk-creating only once per tournament), I don't think it's a dealbreaker.

**Comment by czlee** [comment]
See: https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.Field.default

**Comment by philipbelesky** [comment]
Hmm, actually you may want to check the new implementation at some point @czlee . The old method wasn't properly constructing the list of unused indices of emoji, so could double-assign them. In addition the old one had a fall back of choosing a random emoji from the master list when no more were available, which seems like it would always violate the uniqueness  constraint?

Possibly I'm overthinking this is just a consequence of moving it from a run-once to a run-for-each-team implementation.

**Comment by philipbelesky** [comment]
Reopening as the Anorak tests are failing. Unclear if this is because each individual test creates new teams within the same database (and thus it is running out of possible emoji) or there are random clashes because of the way they are run in parallel or because the tests aren't creating them properly. My brief look at things wasn't particularly conclusive.

**Comment by czlee** [comment]
I'll try to get this going.

**Comment by czlee** [comment]
Root problem: The importer only saves teams to the database after all of them have been processed and created. This was intentional—it prevents input errors from stopping the importer while it's halfway through saving teams, instead holding back database edits until everything looks okay. But it also means that, when `pick_unused_emoji` is called, it won't take into account the emoji that were picked for teams that have been created but not yet saved.

One fix for this is to add a keyword argument `used=` to `pick_unused_emoji` that passes in emoji that should also be excluded from the random selection, then call `pick_unused_emoji` explicitly in the importer. Unfortunately, this annihilates whatever neatness we previously had from removing emoji from the importer altogether.

Another way is to change the default mechanism, by overriding `emoji` if it looks like `None` in `Team.save()`, but I'm not really a fan of overriding `Team.save()`, because it prevents users from being save objects how they want to in the edit database area.

**Comment by czlee** [comment]
Phew. Third time lucky.

It's not that elegant, but it's broadly equivalent to (and hence no less elegant than) what we had before.
