### ISSUE TITLE
Emoji assigner can throw IntegrityError's

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#461]
It looks like it's still possible to generate duplicate emoji in 1.3.0; see the recent error report from app68890702@heroku.com. Unclear if it's a duplicate due to the shear amount of teams, or due to some failure in random generation. Either way it should probably fail more gracefully.

**Comment by czlee** [comment]
Hmm, that's not good.

**Comment by czlee** [comment]
Eugh, okay. Turns out `ModelForm` [creates the object instance on construction](https://github.com/django/django/blob/1.11/django/forms/models.py#L283), which means it populates the default (and hence calls `pick_unused_emoji`) when it constructs the form. In a formset, these are all created when the formset is constructed. Then when the formset is saved, the forms are [saved one by one](https://github.com/django/django/blob/1.11/django/forms/models.py#L774-L786), but of course the objects already all exist before the first one is saved.

So we actually have the same problem as the importer: it creates a bunch of objects without saving them, then saves them all at once, which is why duplicates can happen.

Ideas:

1. Remove the `default` callable and instead populate `emoji` in `Team.save()` (where `short_name` and `long_name` are populated). I'm not a fan of this approach, because it means you can't set an emoji to `None`, which is both (a) annoying and (b) will be guaranteed to crash once you have more teams than available emoji.

2. Write a `TeamFormSet` that overrides the save functions of `ModelFormSet` to use the `used` argument of `pick_unused_emoji`. But this would reach too far into Django's (somewhat esoteric) formset workings for me to feel comfortable.

3. Remove the `default` callable, and basically remove automatic emoji generation from the model layer altogether. Write a function that populates emoji for a collection of teams, intended to be called by importers after teams have (finished) being created. If someone forgets to call it, the emoji just remain `None`.

    This would mean that the emoji field wouldn't be populated with a default in Jet, so if we want that to be populated we'd have to override something there to do so, which would be a little annoying.

4. Leave everything in place, but have a try-except in `Team.save()` that catches for this problem and blanks out `emoji` if it's not unique. This would prevent it from crashing, but would also mean that every so often a team just won't have an `emoji`, which isn't ideal.

5. As for (4), but have it generate a different emoji at save time instead. This would be confusing for a user though, since the emoji they (possibly deliberately) save would keep changing.

**Comment by czlee** [comment]
I sort of think (3) would be easiest. It's annoying that it can't be built in, but the infrastructure for "generated fields" in the command-line importer is a little silly and I wouldn't be sorry about ditching it (it's not used for anything other than emoji).

- The command-line importer would call the emoji generation function in the Anorak subclass (not in the base class), though `BaseTournamentDataImporter._import` would have to be rewritten to return a list of created objects rather than just the number of objects created.
- The visual importer just populates emoji in the view after the formset is saved.
- Jet... we'll have to figure out how to override. I'm sure it's doable, like using [`ModelAdmin.formfield_for_choice_field()`](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_for_choice_field) or something.

**Comment by philipbelesky** [comment]
Agree that (3) sounds good, let me know if you wan't me to look into the Jet side of things.
