### ISSUE TITLE
Feedback form saves blank text answers

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#472]
All of the "Adjudicator Feedback String Answers" seem to be marked as required in the edit database area, even if the questions themselves are not marked as required. IE a blank "extra comments" field or "choose any" will stop database saves.

**Comment by czlee** [comment]
I think this is expected behaviour; the correct way to remove or not to have a string answer is to delete the answer altogether using the "Delete?" checkbox in the right-hand column.

**Comment by philipbelesky** [comment]
Which right-hand column do you mean? The use case here is:

- Person submits feedback as normal; perhaps skips some non-required string fields such as "comments"
- If I go into the edit database area, and navigate to that piece of feedback, and then change a detail (ie unconfirming it) then hit save
- The backend then says "Please correct error below"; which actually means "Please correct error in the Adjudicator Feedback String Answers tab" (it's not obvious this is where the error is
- In that tab any optional answer that is not filled in says "This field is required."

**Comment by czlee** [comment]
Ah, I see... then the _real_ bug is that it's saving those answers in the first place.

I meant that you're meant to check the "DELETE?" boxes:

![image](https://user-images.githubusercontent.com/1725499/28244274-57cf5f90-699b-11e7-86e2-dd20b9b0e0c2.png)

but if it's saving blank fields as database entries, that's a bug. From a quick look at the code, [adjfeedback/forms.py:190](https://github.com/czlee/tabbycat/blob/df2f615/tabbycat/adjfeedback/forms.py#L190) is meant to filter out blank fields so that it only saves answers that actually exist. But probably I forgot that blank string fields are empty strings, not `None`, so the fix should be to drop the `is not None` part.

Does that make sense? Nice catch, btw.

**Comment by czlee** [comment]
Actually, you can't just drop `is not None`, because you have to store zeros and `False` boolean answers. So I guess it should be `is not None or [...] != ""`, which is a little awkward.

**Comment by philipbelesky** [comment]
Ah, lol, when working with a screen size of less than ~1000px those boxes don't actually show up. Which I totally forgot about.

The context for discovering this was actually having to unconfirmed some submissions as per the scenario in #473. 

If `is not None or [...] != ""` does the trick I have no issue with it :p
