### ISSUE TITLE
Better handle missing debateteams error

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#493]
Currently most draw views will crash when a debate team is missing with an `ObjectDoesNotExist`. While this doesn't seem as common as it once did, it might be worth writing a custom handler for this as we did for the unset round issue. I'm imagining essentially a redirect page that briefly explains:

- In X debate there is no AFF/NEG team assigned. This is likely because it was deleted (or perhaps a bug in the Edit Matchups page)
- To fix this that debate needs to either be deleted or have a team assigned
- You can fix this issue in the Edit Matchups area (maybe it could only show this if there are unused teams)(the edit matchups area should be resilient to the issue)
- You can fix this issue in the Edit Database area

**Comment by czlee** [comment]
I remember thinking about this once, and concluding that it would be too hard to do this generically. But thinking about it again, we could probably make a specialized exception in the team properties framework (in `Debate._team_property`), that one of the base views could catch in `dispatch()`?

If we do this, do you think we should keep the big scary warnings in the edit database area around? I guess they wouldn't be _as_ true anymore, since the problem wouldn't be as obscure. (They're just a bit of a hack, and are quite a big chunk of text to translate once we get round to translations.)

**Comment by philipbelesky** [comment]
I've been testing having teams missing to check if the drag/drop UIs can handle it, and the error is almost always thrown in the draw table constructors. So while a generic handler/exception would be nice, I think you'd get 90% of the effect just handling it directly in those views given they are so common.

The big scary warnings in the edit database area are probably still valuable in that (outside of any bugs in the Edit Matchups page) deleting and not recreating a debate team is a user error that should be discouraged.

**Comment by czlee** [comment]
I see. Actually, even handling it in the draw page view would require a specialized exception (this is not a big deal at all), to avoid misdiagnosing other errors. I guess the important thing is that it's possible to get to the matchups page so you can fix it, which mainly requires that the draw page works (since that's where the link is)?

**Comment by philipbelesky** [comment]
Ah yes sorry, I forgot the exception does currently occur in `_team_property` of Debate rather than in the view itself. 

The draw page itself wouldn't necessarily need to work though — the page that the error would redirect you to (ie the 'something bad has happened page') could just link off to the edit matchups page, thus bypassing the draw page entirely. 

That said if possible allowing the draw page to render with missing teams could be useful, if just to prevent all the public-facing pages erroring out when this happens.

**Comment by czlee** [comment]
Wait, I'm a bit confused now. By "generically" I meant "catch it across the entire site", similarly to how we do now with current round. So we'd have to catch in a base view, not in specific views, unless we want to copy and paste this code into dozens of views (many views break with missing teams, not just the draw page). Is that what we want?

Allowing draw pages to render with missing teams could be a bit easier now that we have `tables.py`, but I guess I wouldn't count on it being able to do it without making code really messy. If I remember right, the problem is that if we drop the assumption that `aff_team` (for example) is never `None`, then we have to add exception handling around every time we want to print `aff_team.name`.

**Comment by czlee** [comment]
(Or, what did you mean by "generic handler/exception?")

**Comment by philipbelesky** [comment]
Um never mind about the generic handler/exception, I think I was misunderstanding what you meant earlier. In terms of how exactly this is caught, I don't have a strong preference except for whatever will be easiest and cleanest. If I'm reading you right that sounds like throwing a special exception in `_team_property` which is then caught in the base view for draws, and that when caught redirects to the 'hey fix this' page.

**Comment by czlee** [comment]
Yeah, that's the idea. I mean, we could even catch it in the same place as where the current round exception is caught.

**Comment by czlee** [comment]
I've done a first implementation of a catch-all redirect in 5b91dbc686f07a1b90948601a90e7fef2416cf61. It just redirects to the debate objects change list in Edit Database if it's a superuser logged in, or to the public index with an error message if it's not. It's a start in that it no longer throws a 500, but you probably wanted something a bit more user-friendly?

**Comment by philipbelesky** [comment]
Yea, I've added an intermediary page with detailed instructions on how to fix this, and set the link to the admin area open in a new tab (so people can refer back to those instructions). Check it out and let me know if there's anything unclear about the messages or that should be added.

**Comment by czlee** [comment]
Looks good in principle! One thing about the current implementation is that if you refresh the page (say, accidentally close, then re-open it), the message disappears. I guess ideally we'd want the page to just vet the database again for all offending debates, and present the user with a list? That would render the message redundant, so we could remove it entirely. Alternatively, we could have a means of passing the offending debate to the fix-debates view, but it's probably better to look for all of them.

**Comment by czlee** [comment]
If we _really_ wanted to make life easy for users, we could even provide direct links to the specific Jet pages for the offending debates, rather than just directing them to the Edit Database area for debates :wink: (but do we want to make life that easy for users who have already messed this up once?)

**Comment by philipbelesky** [comment]
True, it's probably worth a shot as (if just from my own experience) it is kind of a pain to identify that particular debate. Have done so in 4ae66076257d9fb07535f02c9e4571a7f3717bce; feel free to close this if that implementation is OK.

**Comment by czlee** [comment]
I went a few steps further :joy: See a3e73f72644932306029cbe0fd2290dba740bd27.

Have a look at it and possibly tidy up a few things if you think necessary, then feel free to close if you're happy with it (or bump it back to me if you're not).
