### ISSUE TITLE
Tabbykitten version marker doesn't work

### ISSUE THREAD

**Issue by czlee** [czlee/tabbycat#499]
Our current strategy of marking Tabbykitten installations doesn't work, because the `&ENV[KITTEN]=true` URL parameters string only works if the environment variable is also listed in the app.json file. We'll need a different strategy. Unfortunately you can't "lock down" an environment variable's value in the app.json file, other than to make it autogenerated with the "secret" generator. But another strategy could just be to define the `KITTEN` variable, and judge whether it's Tabbykitten based on the presence or absence of the variable, without checking its value.

**Comment by philipbelesky** [comment]
So that would look like just defining a new item in the `env` of `app.json` (maybe having it use the secret generator so users cannot edit it when deploying) and change:

`if os.environ.get('KITTEN', '') == 'true':`

to just

`if os.environ.get('KITTEN', ''):`

Or do you mean just defining a `KITTEN` variable in settings?

**Comment by czlee** [comment]
In my head I was thinking an environment variable (tested using `if 'KITTEN' in os.environ:`), but now that you mention it, a `KITTEN` variable in settings is probably smarter.

**Comment by philipbelesky** [comment]
Ok cool, I've added the environment variable in the kitten branch and removed the environment variable links from the documentation in develop. There will probably be a merge conflict next time we merge into kitten but after that it should be all good.
