### ISSUE TITLE
Implement automated unit tests to verify core functionality

### ISSUE THREAD

**Issue by philipbelesky** [czlee/tabbycat#71]
In order to prevent regressions automated tests should be created to verify the results of the draw and any other critical functionality. At the least these tests should involve using real data from past tournaments to generate draw matchups and verifying these matchups against the results from past tournaments. For completeness, the data should include tournaments run on both tabby cat (Australs '08/'10) and other programs (Australian Easters, UADC, etc).

I'll need to look into exactly how Django's ```unittest``` module operates, but ideally it would input the results round-by-round, and raise exceptions if a particular round does not match the historic result.

To expand test coverage, the above mentioned historic data sets could be merged with randomly generated data (such as unconfirmed ballots) that should not affect the draw functionality.

**Comment by philipbelesky** [comment]
Is such a broad-ranging issue still relevant? Maybe we could break it into more specific instances where tests are needed?

**Comment by czlee** [comment]
Yeah, I've often thought this. Also, realistically we're probably years away from having satisfactory coverage in unit tests.

That said, the above comment thread seems to suggest something more specific, namely, simulating an entire pre-determined tournament. Did you still want to do that? It's probably arguable whether such a high-level test is appropriate given its inevitable lack of coverage, and also since it's not clear to me whether an "entire tournament" test would pick up things that smaller, more targeted tests would not. Also, there's randomness in the draws&mdash;side allocations are random of both teams have had the same number of affs&mdash;and as you progress further through the tournament, the number of possible correct paths correct increases, I suspect exponentially.

**Comment by philipbelesky** [comment]
Yea I think the pre-determined tournament thing is better dealt with through focused tests. Plus in attempting to write tests for the new break rounds I've found building a fixture that represents a full tournament with fidelity incredibly difficult unless the data can be easily imported. Having a simplified version of results from a relatively recent major tournaments as a fixture would be a great resource for testing draw/break rules changes though.

Close this issue then? Or is there some value to having it around?

**Comment by czlee** [comment]
Yeah, I agree, I think this is what has stopped me writing rigorous tests in the past. We might need to work on a framework for this, but it'll be hard to get it to cover a good range of cases so it's questionable that it's a worthwhile exercise - it might make more sense just to create a new tournament for each test case.

No, can be closed.
